# Generated by Django 4.2.7 on 2023-12-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('PositiveCount', models.IntegerField()),
                ('NeutralCount', models.IntegerField()),
                ('NegativeCount', models.IntegerField()),
            ],
        ),
    ]
