# Generated by Django 4.2.7 on 2023-12-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_timelinesong_artist_alter_timelineartist_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistByRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('song_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
